### ISSUE TITLE
Android: Add 16 KB page alignment support for Android 15+

### ISSUE THREAD

**Issue by akj-07** [appsinacup/godot-rapier-physics#390]
### Problem
For Godot 4.5+, Rapier 2D does not support building from scratch. I tried to build it directly to fix the 16KB page alignment issue for Android, but some libraries need updates to work with the 4.5 version.

### Details
- **Godot Version**: 4.5
- **Current Issue**: `libgodot_rapier.android.aarch-64-linux-android.so` has 4KB page alignment
- **Required**: 16KB page alignment for Android 15+ compatibility

**Comment by akj-07** [comment]
Thanks for the quick response! Let me clarify:

## The Two Issues We're Facing

### Issue 1: 16KB Page Alignment Requirement
- Google Play now requires all native libraries (.so files) to have 16KB page alignment for Android 15+ devices
- Current Rapier binaries (e.g., `libgodot_rapier.android.aarch-64-linux-android.so`) are compiled with 4KB alignment
- This causes apps to fail on newer Android devices with 16KB page sizes

### Issue 2: Can't Rebuild from Source with Godot 4.5
When attempting to rebuild Rapier with 16KB alignment for Godot 4.5, compilation fails with these errors:
error[E0407]: method set_collision_layer is not a member of trait IPhysicsDirectBodyState2DExtension
error[E0407]: method get_collision_layer is not a member of trait IPhysicsDirectBodyState2DExtension
error[E0407]: method set_collision_mask is not a member of trait IPhysicsDirectBodyState2DExtension
error[E0407]: method get_collision_mask is not a member of trait IPhysicsDirectBodyState2DExtension

**Comment by akj-07** [comment]
Hi, thanks for the clarification!

I understand that your Godot 4.5 build works without any changes to the TOML file. In my case, I was hitting page size issues on Android with the default export templates, which is why I temporarily added the -Wl,-z,max-page-size=16384 flag.

It’s now clear that these TOML changes are not related to the trait errors (set_collision_layer, get_collision_layer, etc.) — those are caused by differences in the Godot 4.5 GDExtension API.

I’ll make sure to revert my TOML changes and focus on aligning the Rust source with the Godot 4.5 API.

Thanks again for confirming!

**Comment by akj-07** [comment]
I had not tested the earlier build and modified the config.toml file directly. When i moved a step back and retried it, the config was the main issue.

Still a line change would be requied in the current rapier build to make it eligible for the current android requirement. 

Here are my changes that i made in the working config.toml file to match the page alignment issue,

```
[target.armv7-linux-androideabi]
linker = "armv7a-linux-androideabi23-clang"
rustflags = ["-C", "link-arg=-Wl,-z,max-page-size=16384"]

[target.aarch64-linux-android]
linker = "aarch64-linux-android23-clang"
rustflags = ["-C", "link-arg=-Wl,-z,max-page-size=16384"]

[target.x86_64-linux-android]
linker = "x86_64-linux-android23-clang"
rustflags = ["-C", "link-arg=-Wl,-z,max-page-size=16384"]

[target.i686-linux-android]
linker = "i686-linux-android23-clang"
rustflags = ["-C", "link-arg=-Wl,-z,max-page-size=16384"]

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"

[target.armv7-unknown-linux-gnueabihf]
linker = "arm-linux-gnueabihf-gcc"
```
